const canvas = document.querySelector('#matrix');
const ctx = canvas.getContext('2d');
let columns = [], w = 0, h = 0;
function resize(){w=canvas.width=innerWidth*devicePixelRatio;h=canvas.height=innerHeight*devicePixelRatio;const size=18*devicePixelRatio;columns=Array(Math.ceil(w/size)).fill(0).map(()=>Math.random()*-80);ctx.font=`${size}px monospace`}
function rain(){ctx.fillStyle='rgba(7,10,10,.075)';ctx.fillRect(0,0,w,h);const size=18*devicePixelRatio;ctx.fillStyle='rgba(54,130,96,.5)';columns.forEach((y,i)=>{if(Math.random()>.65)ctx.fillText(Math.random()>.5?'1':'0',i*size,y*size);columns[i]=y*size>h&&Math.random()>.985?0:y+.24});requestAnimationFrame(rain)}
resize();rain();addEventListener('resize',resize);
const system=document.querySelector('#system');
const title=document.querySelector('.hero h1');
const rawTitle=title.innerHTML;
title.innerHTML='';
rawTitle.split(/(<br>)/i).forEach((part,group)=>{
  if(part.toLowerCase()==='<br>'){title.appendChild(document.createElement('br'));return}
  const word=document.createElement('span');word.className='morph-word';
  [...part].forEach((ch,i)=>{const s=document.createElement('span');s.className='morph-char';s.textContent=ch;const seed=i+group*19;const side=seed%2?1:-1;const x=side*(85+((seed*47)%260));const y=((seed*83)%360)-180;const r=side*(12+((seed*29)%48));const scale=.55+((seed*17)%55)/100;s.style.setProperty('--mx',`${x}px`);s.style.setProperty('--my',`${y}px`);s.style.setProperty('--mr',`${r}deg`);s.style.setProperty('--ms',scale);s.style.setProperty('--delay',`${.28+((seed*13)%22)*.025}s`);word.appendChild(s)});title.appendChild(word)
});
requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelectorAll('.morph-char').forEach(c=>c.classList.add('settled'))));
document.querySelector('.hero').addEventListener('pointermove',e=>{if(innerWidth<900)return;const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*10;system.style.transform=`translate(${x}px,${y}px) rotateX(${-y/4}deg) rotateY(${x/4}deg)`});
document.querySelector('.menu').addEventListener('click',()=>document.querySelector('.topbar').classList.toggle('open'));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.15});document.querySelectorAll('.section').forEach(e=>io.observe(e));

const cardIds=['philosophy','principles','architecture','research','mos','experiment','mirror','stewardship'];
const cards=cardIds.map(id=>document.getElementById(id));let activeCard=-1;
const cardUi=document.querySelector('.card-ui'),counter=document.querySelector('.card-counter'),indexPanel=document.querySelector('.index-panel');
function openCard(id){const next=cardIds.indexOf(id);if(next<0&&id!=='contact')return;closeIndex();document.querySelectorAll('.section.card-active').forEach(c=>c.classList.remove('card-active'));const target=document.getElementById(id);if(!target)return;target.classList.add('card-active');activeCard=next;document.body.classList.add('card-open');cardUi.setAttribute('aria-hidden','false');cardUi.classList.toggle('contact-mode',id==='contact');counter.textContent=next>=0?`${String(next+1).padStart(2,'0')} / ${String(cardIds.length).padStart(2,'0')}`:'THRESHOLD';location.hash=id}
function closeCard(){document.querySelectorAll('.section.card-active').forEach(c=>c.classList.remove('card-active'));document.body.classList.remove('card-open');cardUi.setAttribute('aria-hidden','true');activeCard=-1;history.replaceState(null,'',location.pathname+location.search)}
function stepCard(dir){if(activeCard<0)return;openCard(cardIds[(activeCard+dir+cardIds.length)%cardIds.length])}
function openIndex(){closeLegal();closeCard();indexPanel.classList.add('open');indexPanel.setAttribute('aria-hidden','false');document.body.classList.add('index-open')}
function closeIndex(){indexPanel.classList.remove('open');indexPanel.setAttribute('aria-hidden','true');document.body.classList.remove('index-open')}
document.querySelectorAll('[data-card]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openCard(el.dataset.card)}));
document.querySelectorAll('[data-open-index]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openIndex()}));
document.querySelector('.index-close').addEventListener('click',closeIndex);document.querySelector('.card-close').addEventListener('click',closeCard);document.querySelector('.card-prev').addEventListener('click',()=>stepCard(-1));document.querySelector('.card-next').addEventListener('click',()=>stepCard(1));
const nodeMap={n1:'philosophy',n2:'principles',n3:'research',n4:'mos',n5:'architecture',n6:'mirror',n7:'experiment',n8:'mos'};Object.entries(nodeMap).forEach(([cls,id])=>{const n=document.querySelector('.'+cls);if(n){n.tabIndex=0;n.setAttribute('role','button');n.addEventListener('click',()=>openCard(id));n.addEventListener('keydown',e=>{if(e.key==='Enter')openCard(id)})}});
document.querySelector('.hero .primary').addEventListener('click',e=>{e.preventDefault();openCard('philosophy')});document.querySelector('.hero .secondary').addEventListener('click',e=>{e.preventDefault();openCard('mos')});
document.querySelectorAll('[data-home]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();closeIndex();closeLegal();closeCard()}));
const legalPanel=document.querySelector('.legal-panel');function openLegal(){closeIndex();closeCard();legalPanel.classList.add('open');legalPanel.setAttribute('aria-hidden','false');document.body.classList.add('legal-open')}function closeLegal(){if(!legalPanel)return;legalPanel.classList.remove('open');legalPanel.setAttribute('aria-hidden','true');document.body.classList.remove('legal-open')}
document.querySelectorAll('[data-open-legal]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openLegal()}));document.querySelector('.legal-close').addEventListener('click',closeLegal);document.querySelectorAll('[data-legal-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-legal-tab]').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('[data-legal-sheet]').forEach(s=>s.classList.toggle('active',s.dataset.legalSheet===btn.dataset.legalTab))}));
addEventListener('keydown',e=>{if(e.key==='Escape'){if(document.body.classList.contains('legal-open'))closeLegal();else if(document.body.classList.contains('index-open'))closeIndex();else closeCard()}if(e.key==='ArrowRight'&&!document.body.classList.contains('legal-open'))stepCard(1);if(e.key==='ArrowLeft'&&!document.body.classList.contains('legal-open'))stepCard(-1)});
if(cardIds.includes(location.hash.slice(1))||location.hash==='#contact')openCard(location.hash.slice(1));

// Bilingual thought system — semantic German, never automatic machine translation.
const de={
'Index':'Index','Mandate':'Mandat','Contact':'Kontakt','Legal':'Rechtliches','Operational Reasoning Systems':'Operative Denksysteme','Industry has more data than ever.':'Die Industrie verfügt über mehr Daten als je zuvor.','And less':'Und versteht','understanding':'sich selbst','of itself.':'immer weniger.','A new discipline for how industrial':'Eine neue Disziplin dafür, wie industrielle','organizations observe, decide and learn.':'Organisationen beobachten, entscheiden und lernen.','Begin observation':'Beobachtung beginnen','Explore MOS':'MOS erkunden','Human':'Mensch','Experience':'Erfahrung','Standards':'Standards','& Principles':'& Prinzipien','Data':'Daten','Signals':'Signale','Process':'Prozess','Reality':'Realität','Outcomes':'Ergebnisse','Truth':'Wahrheit','AI Models':'KI-Modelle','Reasoning':'Schlussfolgern','Decision':'Entscheidung','& Action':'& Handlung','Intent':'Absicht','Decision Logic':'Entscheidungslogik',
'The premise':'Die Prämisse','Every organization thinks.':'Jede Organisation denkt.','Very few understand how.':'Nur wenige verstehen, wie.','MODEL 01':'MODELL 01','INFORMATION DOES NOT EQUAL UNDERSTANDING':'INFORMATION IST NICHT VERSTÄNDNIS','OPERATIONAL REASONING':'OPERATIVES SCHLUSSFOLGERN','INPUT':'EINGANG','INFORMATION':'INFORMATION','More data':'Mehr Daten','More reports':'Mehr Berichte','More activity':'Mehr Aktivität','UNRESOLVED':'UNGEKLÄRT','UNCERTAINTY':'UNSICHERHEIT','What changed?':'Was hat sich verändert?','What remained stable?':'Was blieb stabil?','What is evidence?':'Was ist Evidenz?','GATE':'SCHWELLE','DECISION':'ENTSCHEIDUNG','Action occurs':'Handlung erfolgt','whether understanding':'unabhängig davon, ob','exists or not.':'Verständnis besteht.','REQUIRED STATE':'ERFORDERLICHER ZUSTAND','UNDERSTANDING':'VERSTÄNDNIS','Uncertainty reduced':'Unsicherheit reduziert','before action.':'vor der Handlung.','OBSERVATION':'BEOBACHTUNG','Operational excellence is not created by collecting more information.':'Operative Exzellenz entsteht nicht durch das Sammeln weiterer Informationen.','It is created by reducing uncertainty before making decisions.':'Sie entsteht, indem Unsicherheit vor einer Entscheidung reduziert wird.',
'First principles':'Erste Prinzipien','What remains true.':'Was wahr bleibt.','Principles that survive contact with reality.':'Prinzipien, die der Wirklichkeit standhalten.','Every deviation is the consequence of one or more changes relative to a stable reference state.':'Jede Abweichung ist die Folge einer oder mehrerer Veränderungen gegenüber einem stabilen Referenzzustand.','Observation begins where assumptions end.':'Beobachtung beginnt dort, wo Annahmen enden.','Information exists only to improve the next decision.':'Information existiert nur, um die nächste Entscheidung zu verbessern.','Routine processes define reality.':'Routineprozesse definieren die Wirklichkeit.','Organizations fail when they cannot distinguish signal from noise.':'Organisationen scheitern, wenn sie Signal und Rauschen nicht unterscheiden können.',
'The hidden architecture of operational reality':'Die verborgene Architektur operativer Wirklichkeit','The visible problem is rarely the whole problem.':'Das sichtbare Problem ist selten das ganze Problem.','It is the point at which the hidden structure becomes observable.':'Es ist der Punkt, an dem die verborgene Struktur beobachtbar wird.','Relation':'Beziehung','Nothing becomes a deviation by itself. It becomes one through comparison.':'Nichts wird aus sich selbst zur Abweichung. Erst der Vergleich macht es dazu.','Causation':'Kausalität','Every changed outcome requires at least one changed condition.':'Jedes veränderte Ergebnis setzt mindestens eine veränderte Bedingung voraus.','Correspondence':'Entsprechung','Local patterns can reveal the architecture of the wider system.':'Lokale Muster können die Architektur des größeren Systems offenlegen.','Rhythm':'Rhythmus','A single measurement describes a state. A sequence reveals a system.':'Eine einzelne Messung beschreibt einen Zustand. Eine Folge offenbart ein System.','Polarity':'Polarität','What is and what is not define one another.':'Was ist und was nicht ist, definiert sich gegenseitig.','Observation':'Beobachtung','The observer is part of the system being observed.':'Der Beobachter ist Teil des beobachteten Systems.','Transformation':'Transformation','Understanding is proven only through a different, stable state.':'Verständnis beweist sich erst in einem anderen, stabilen Zustand.',
'The observatory':'Das Observatorium','Research begins where the existing model no longer explains reality.':'Forschung beginnt dort, wo das bestehende Modell die Wirklichkeit nicht mehr erklärt.','Questions before answers.':'Fragen vor Antworten.','OPEN FIELD OF INQUIRY':'OFFENES FORSCHUNGSFELD','STATUS / IN PROGRESS':'STATUS / IN ARBEIT','UNEXPLAINED':'UNERKLÄRTE','Operational':'Operatives','Observation Theory':'Beobachtungstheorie','Industrial':'Industrielle','Cognition':'Kognition','Decision Systems':'Entscheidungssysteme','Organizational':'Organisationale','Entropy':'Entropie','Manufacturing':'Produktions-','Operating Systems':'Betriebssysteme','METHOD':'METHODE','Observation in practice':'Beobachtung in der Praxis','OPEN CONNECTIONS INDICATE UNRESOLVED RELATIONSHIPS':'OFFENE VERBINDUNGEN ZEIGEN UNGEKLÄRTE BEZIEHUNGEN',
'The operational vessel':'Das operative Gefäß','The first Operational Reasoning System.':'Das erste operative Denksystem.','MANUFACTURING OPERATING SYSTEM':'MANUFACTURING OPERATING SYSTEM','DEVIATION → KNOWLEDGE':'ABWEICHUNG → WISSEN','STABLE REFERENCE':'STABILE REFERENZ','Routine':'Routine','Standard · Expected state · Repetition':'Standard · Erwarteter Zustand · Wiederholung','CHANGED CONDITION':'VERÄNDERTE BEDINGUNG','Change':'Veränderung','Known · Unknown · Suspected':'Bekannt · Unbekannt · Vermutet','VISIBLE SIGNAL':'SICHTBARES SIGNAL','Deviation':'Abweichung','Reality no longer matches reference':'Wirklichkeit entspricht nicht mehr der Referenz','Separate fact from assumption':'Fakt von Annahme trennen','Where · What · When · Extent':'Wo · Was · Wann · Ausmaß','Boundary · Contrast · Exclusion':'Grenze · Kontrast · Ausschluss','COMPARISON':'VERGLEICH','EVIDENCE':'EVIDENZ','Change analysis':'Veränderungsanalyse','Stable comparison':'Stabiler Vergleich','Clean point':'Reiner Vergleichspunkt','Signal integrity':'Signalintegrität','RESIDUAL UNCERTAINTY':'RESTUNSICHERHEIT','Reduced before decision':'Vor Entscheidung reduziert','CONTROLLED CHANGE':'KONTROLLIERTE VERÄNDERUNG','Action':'Handlung','Owner · Time · Evidence':'Verantwortung · Zeit · Evidenz','PROOF':'NACHWEIS','Effectiveness':'Wirksamkeit','Different and stable state':'Anderer und stabiler Zustand','LEARNING':'LERNEN','Rewrite the reference':'Referenz neu schreiben','New routine · New standard · Preserved knowledge':'Neue Routine · Neuer Standard · Bewahrtes Wissen','PRINCIPLE':'PRINZIP','A deviation becomes knowledge only when learning changes the next routine.':'Eine Abweichung wird erst dann zu Wissen, wenn Lernen die nächste Routine verändert.','BEGIN OBSERVATION ◇':'BEOBACHTUNG BEGINNEN ◇',
'The shared experiment':'Das gemeinsame Experiment','One real problem. Before any promise.':'Ein reales Problem. Vor jedem Versprechen.','Proof of Philosophy.':'Beweis der Philosophie.','MUTUAL OBSERVATION':'GEMEINSAME BEOBACHTUNG','NO OBLIGATION':'KEINE VERPFLICHTUNG','ORGANIZATION':'ORGANISATION','REAL':'REALES','PROBLEM':'PROBLEM','WORKING':'FUNKTIONIERENDES','MODULE':'MODUL','SYNAPTRON':'SYNAPTRON','DIFFERENT REALITY':'UNTERSCHIEDLICHE WIRKLICHKEIT','Respectfully separate':'Respektvoll trennen','JOINT OBSERVATION':'GEMEINSAME BEOBACHTUNG','SHARED REALITY':'GETEILTE WIRKLICHKEIT','Continue together':'Gemeinsam fortfahren','MEASURE':'MASSSTAB','Shared understanding — not a signed contract.':'Gemeinsames Verständnis – kein unterschriebener Vertrag.','PROOF OF PHILOSOPHY':'BEWEIS DER PHILOSOPHIE',
'The mirror':'Der Spiegel','AI can extend observation. It cannot inherit accountability.':'KI kann Beobachtung erweitern. Verantwortung kann sie nicht übernehmen.','Reduce uncertainty. Preserve decision.':'Unsicherheit reduzieren. Entscheidung bewahren.','ARTIFICIAL INTELLIGENCE':'KÜNSTLICHE INTELLIGENZ','ACCOUNTABILITY BOUNDARY ACTIVE':'VERANTWORTUNGSGRENZE AKTIV','OPERATIONAL REALITY':'OPERATIVE WIRKLICHKEIT','REVEALED':'SICHTBAR GEMACHT','CONTRADICTION':'WIDERSPRUCH','PATTERN':'MUSTER','BOUNDARY':'GRENZE','HUMAN':'MENSCH','DECISION +':'ENTSCHEIDUNG +','ACCOUNTABILITY':'VERANTWORTUNG','LIMIT':'GRENZE','Observation may be extended. Accountability cannot be delegated.':'Beobachtung kann erweitert werden. Verantwortung kann nicht delegiert werden.','HUMAN DECISION':'MENSCHLICHE ENTSCHEIDUNG',
'The mandate':'Das Mandat','You do not pay us to solve yesterday\'s problem.':'Sie bezahlen uns nicht dafür, das Problem von gestern zu lösen.','You mandate us to preserve the ability to understand tomorrow\'s.':'Sie mandatieren uns, die Fähigkeit zu bewahren, das Problem von morgen zu verstehen.','OPERATIONAL STEWARDSHIP':'OPERATIVE SYSTEMVERANTWORTUNG','TWO ECONOMIC LOGICS':'ZWEI ÖKONOMISCHE LOGIKEN','Proof of Philosophy':'Beweis der Philosophie','ONE REAL':'EIN REALES','NO FEE':'OHNE HONORAR','Working module':'Funktionierendes Modul','Inside the real environment':'In der realen Umgebung','Joint observation':'Gemeinsame Beobachtung','Mutual decision':'Gemeinsame Entscheidung','No commitment before value exists.':'Keine Verpflichtung, bevor Wert entstanden ist.','DO WE SEE':'SEHEN WIR','THE SAME':'DIESELBE','REALITY?':'WIRKLICHKEIT?','NO → SEPARATE':'NEIN → TRENNEN','YES → CONTINUE':'JA → FORTFAHREN','Stewardship Mandate':'Mandat zur Systemverantwortung','SYSTEM':'SYSTEM-','CAPABILITY':'FÄHIGKEIT','PAID':'VERGÜTET','System Stewardship':'Systemverantwortung','System Architecture':'Systemarchitektur','Operational Intervention':'Operative Intervention','Preserve and extend the organization\'s ability to reason.':'Die Denkfähigkeit der Organisation bewahren und erweitern.','REFERENCE FIELD':'REFERENZFELD','Responsibility can be supported. Accountability remains with the organization.':'Verantwortung kann unterstützt werden. Rechenschaft bleibt bei der Organisation.','MANAGEMENT SYSTEM STEWARDSHIP':'MANAGEMENTSYSTEM-VERANTWORTUNG',
'The threshold':'Die Schwelle','Bring one real problem.':'Bringen Sie ein reales Problem.','No presentation is required.':'Keine Präsentation erforderlich.','ENTRY FIELD':'EINGANGSFELD','BEGIN OBSERVATION':'BEOBACHTUNG BEGINNEN','NO SALES PROCESS':'KEIN VERKAUFSPROZESS','OBSERVABLE REALITY':'BEOBACHTBARE WIRKLICHKEIT','Describe what is happening.':'Beschreiben Sie, was geschieht.','Before explaining why.':'Bevor Sie erklären, warum.','Phenomenon':'Phänomen','Impact':'Auswirkung','Boundary':'Grenze','First observation':'Erste Beobachtung','No deck. No requirement specification. One real operational problem.':'Keine Folien. Kein Lastenheft. Ein reales operatives Problem.','THE THRESHOLD':'DIE SCHWELLE','OBSERVE BEFORE INTERPRETING':'BEOBACHTEN VOR INTERPRETIEREN','DIRECT CHANNEL':'DIREKTER KANAL','Begin with the problem.':'Beginnen Sie mit dem Problem.','Write the first observable facts. Nothing more is required.':'Schreiben Sie die ersten beobachtbaren Fakten. Mehr ist nicht erforderlich.','QUESTION':'FRAGE','What if organizations could actually reason?':'Was wäre, wenn Organisationen tatsächlich schlussfolgern könnten?','ONE REAL PROBLEM':'EIN REALES PROBLEM',
'Synaptron Index':'Synaptron Index','Knowledge Plates':'Erkenntnistafeln','The Premise':'Die Prämisse','Information ≠ Understanding':'Information ≠ Verständnis','First Principles':'Erste Prinzipien','Stable reference':'Stabile Referenz','Hidden Architecture':'Verborgene Architektur','Seven relations':'Sieben Beziehungen','The Observatory':'Das Observatorium','Open inquiry':'Offene Forschung','Operational Vessel':'Operatives Gefäß','Shared Experiment':'Gemeinsames Experiment','Artificial Intelligence':'Künstliche Intelligenz','The Mandate':'Das Mandat',
'Synaptron Legal':'Synaptron Rechtliches','Entity & Privacy':'Unternehmen & Datenschutz','Legal Entity':'Impressum','Privacy':'Datenschutz','Provider Information':'Anbieterinformationen','LEGAL ENTITY':'RECHTSTRÄGER','REPRESENTED BY':'VERTRETEN DURCH','Shareholder and Managing Director':'Gesellschafter und Geschäftsführer','with sole signature authority':'mit Einzelzeichnungsberechtigung','REGISTRATION':'REGISTRIERUNG','Commercial Register Canton Schwyz':'Handelsregister Kanton Schwyz','CONTACT':'KONTAKT','The company is registered in Einsiedeln, Canton Schwyz, Switzerland.':'Das Unternehmen ist in Einsiedeln, Kanton Schwyz, Schweiz, eingetragen.','Privacy Notice':'Datenschutzerklärung'
};
const originalText=new Map();
const translatableRoot=document.body;
function textNodes(root){const out=[];const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&n.parentElement.closest('script,style')?NodeFilter.FILTER_REJECT:n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});while(walker.nextNode())out.push(walker.currentNode);return out}
textNodes(translatableRoot).forEach(n=>originalText.set(n,n.nodeValue));
function applyLanguage(lang){const previous=document.body.dataset.lang;document.documentElement.lang=lang;document.body.dataset.lang=lang;textNodes(translatableRoot).forEach(n=>{if(!originalText.has(n))originalText.set(n,n.nodeValue);const raw=originalText.get(n),trim=raw.trim();if(!trim)return;const value=lang==='de'?(de[trim]||trim):trim;n.nodeValue=raw.replace(trim,value)});if(lang==='de')title.innerHTML='Und versteht<br>sich selbst<br>immer weniger.';else if(previous==='de')title.innerHTML='And less<br>understanding<br>of itself.';document.querySelector('.language-switch').textContent=lang==='de'?'EN':'DE';document.querySelector('.language-switch').setAttribute('aria-label',lang==='de'?'Switch to English':'Auf Deutsch wechseln');localStorage.setItem('synaptron-language',lang)}
document.querySelector('.language-switch').addEventListener('click',()=>applyLanguage(document.documentElement.lang==='de'?'en':'de'));
applyLanguage(localStorage.getItem('synaptron-language')||'en');
